{
 "title": "BeeGFS I/O Metadata Rates by User/Client/Node",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "colo", "query": "Site" },
   { "name": "name", "label": "Name", "query": "BeeGFS" },
   { "name": "host", "label": "Host", "query": "stats-server-hostname" },
   { "name": "bandwidth", "query": "25000000000" },
   {
    "name": "buckets",
    "label": "Buckets",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "mode", "label": "Mode", "query": "user,client" },
   {
    "name": "pie_metric",
    "label": "User/Client Pie",
    "query": "ack_rate,close_rate,create_rate,createLI_rate,dirparent_rate,entInf_rate,getXA_rate,hardlnk_rate,mdsInf_rate,mirror_rate,mkdir_rate,nodeInf_rate,open_rate,rddir_rate,ren_rate,revalLI_rate,rmdir_rate,sAttr_rate,sChDrct_rate,statfs_rate,statLI_rate,stat_rate,sum_rate,trunc_rate,unlnk_rate"
   },
   {
    "name": "metric_a",
    "label": "User/Client Graph A",
    "query": "None,ack_rate,close_rate,create_rate,createLI_rate,dirparent_rate,entInf_rate,getXA_rate,hardlnk_rate,mdsInf_rate,mirror_rate,mkdir_rate,nodeInf_rate,open_rate,rddir_rate,ren_rate,revalLI_rate,rmdir_rate,sAttr_rate,sChDrct_rate,statfs_rate,statLI_rate,stat_rate,sum_rate,trunc_rate,unlnk_rate"
   },
   {
    "name": "metric_b",
    "label": "User/Client Graph B",
    "query": "None,ack_rate,close_rate,create_rate,createLI_rate,dirparent_rate,entInf_rate,getXA_rate,hardlnk_rate,mdsInf_rate,mirror_rate,mkdir_rate,nodeInf_rate,open_rate,rddir_rate,ren_rate,revalLI_rate,rmdir_rate,sAttr_rate,sChDrct_rate,statfs_rate,statLI_rate,stat_rate,sum_rate,trunc_rate,unlnk_rate"
   },
   { "name": "show_bsy", "label": "Bsy", "query": "Show,Hide" },
   { "name": "show_qlen", "label": "Qlen", "query": "Show,Hide" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT count(distinct(\"$mode\")) FROM (SELECT first(\"sum\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = '$mode') GROUP BY \"$mode\" LIMIT 1) WHERE $timeFilter GROUP BY time($buckets) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vnas01" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "group" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name $mode Metadata Rates $metric_a/$metric_b ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    {
     "format": "iops",
     "label": "<--- Graph B ----- Graph A --->"
    }
   ],
   "targets": [
    {
     "alias": "a.$metric_a.[[tag_user]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$mode\" FROM (SELECT last(\"$metric_a\") AS \"user\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'user') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "$metric_a" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "$mode" }
     ]
    },
    {
     "alias": "b.${metric_b}.[[tag_user]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$mode\" FROM (SELECT last(\"$metric_b\") AS \"user\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'user') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "$metric_b" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "user" }
     ]
    },
    {
     "alias": "a.$metric_a.[[tag_client]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$mode\" FROM (SELECT last(\"$metric_a\") AS \"client\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'client') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"client\"",
     "select": [
      [
       { "params": [ "$metric_a" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "client" }
     ]
    },
    {
     "alias": "b.$metric_b.[[tag_client]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$mode\" FROM (SELECT last(\"$metric_b\") AS \"client\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'client') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"client\"",
     "select": [
      [
       { "params": [ "$metric_b" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "client" }
     ]
    },
    {
     "alias": "TotalA $metric_a",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"$metric_a\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_user') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "$metric_a" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    },
    {
     "alias": "TotalB $metric_b",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"$metric_b\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_user') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "$metric_b" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 3 },
   "format": "iops",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "$mode" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"$pie_metric\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_$mode') AND $timeFilter",
     "select": [
      [
       { "params": [ "$pie_metric" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "$mode" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name $mode $metric_a",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "$mode" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT max(\"read_rate\") FROM \"tail\" WHERE (\"host\" = 'vnas01' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "$pie_metric" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "$pie_metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "$mode" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<style>\n.hr-text {\n  line-height: 1em;\n  position: relative;\n  outline: 0;\n  border: 0;\n  color: black;\n  text-align: center;\n  height: 1.5em;\n  opacity: .5;\n  font-family: Futura, sans-serif;\n}\n.hr-text:before {\n  content: '';\n  background: -webkit-gradient(linear, left top, right top, from(transparent), color-stop(#818078), to(transparent));\n  background: linear-gradient(to right, transparent, #FFFFFF, transparent);\n  position: absolute;\n  left: 0;\n  top: 50%;\n  width: 100%;\n  height: 1px;\n}\n.hr-text:after {\n  content: attr(data-content);\n  position: relative;\n  display: inline-block;\n  color: black;\n  padding: 0 .5em;\n  line-height: 1.5em;\n  color: #FFFFFF;\n  background-color: #161719;\n  white-space: pre;\n  margin-top: -9px;\n}\n</style>\n<table align=\"center\" width=\"100%\" height=\"100%\" style=\"border: 0px\">\n  <tr><td style=\"border: 0px\">\n    <hr align=\"center\" class=\"hr-text\" data-content=\"^ USERS/CLIENTS ^\nv NODES v\">\n  </td></tr>\n</table>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT count(distinct(\"server\")) FROM (SELECT first(\"bsy\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY \"server\" fill(none)) WHERE $timeFilter GROUP BY time($buckets)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vnas01" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "group" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Node Metadata Requests ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Reqs" }
   ],
   "targets": [
    {
     "alias": "reqs.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"reqs\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(0)",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "Total Reqs",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"reqs\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 0, "y": 15 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "measurement": "tail",
     "query": "SELECT last(\"reqs\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') AND $timeFilter",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Metadata Reqs",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT max(\"read_rate\") FROM \"tail\" WHERE (\"host\" = 'vnas01' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "reqs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Metadata Bsy",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT last(\"total_rate\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "bsy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Node Data Bsy/Qlen ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "<--- Qlen ----- Bsy --->" }
   ],
   "targets": [
    {
     "alias": "bsy.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_bsy\" FROM (SELECT last(\"bsy\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "qlen.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_qlen\" FROM (SELECT last(\"qlen\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "Total Bsy",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_bsy\" FROM (SELECT last(\"bsy\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    },
    {
     "alias": "Total Qlen",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_qlen\" FROM (SELECT last(\"qlen\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    }
   ]
  }
 ]
}