{
 "title": "BeeGFS Total Data I/O by User/Client/Node",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "colo", "query": "Site" },
   { "name": "name", "label": "Name", "query": "BeeGFS" },
   { "name": "host", "label": "Host", "query": "stats-server-hostname" },
   {
    "name": "buckets",
    "label": "Buckets",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "mode", "label": "Mode", "query": "user,client" },
   {
    "name": "metric_a",
    "label": "User/Client Graph A",
    "query": "None,ack,close,getFSize,hrtbeat,nodeInf,ops-rd,ops-wr,read_bytes,rw_bytes,sAttr,sChDrct,statfs,storInf,sum,trunc,unlnk,write_bytes"
   },
   {
    "name": "metric_b",
    "label": "User/Client Graph B",
    "query": "None,ack,close,getFSize,hrtbeat,nodeInf,ops-rd,ops-wr,read_bytes,rw_bytes,sAttr,sChDrct,statfs,storInf,sum,trunc,unlnk,write_bytes"
   },
   { "name": "show_bsy", "label": "Node Bsy", "query": "Show,Hide" },
   { "name": "show_qlen", "label": "Node Qlen", "query": "Show,Hide" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT count(distinct(\"user\")) FROM (SELECT first(\"read_rate\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'user') GROUP BY \"user\" fill(none)) WHERE $timeFilter GROUP BY time($buckets) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vnas01" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "group" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT count(distinct(\"client\")) FROM (SELECT first(\"read_rate\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'client') GROUP BY \"client\" fill(none)) WHERE $timeFilter GROUP BY time($buckets) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vnas01" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "group" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT count(distinct(\"server\")) FROM (SELECT first(\"read_rate\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY \"server\" fill(none)) WHERE $timeFilter GROUP BY time($buckets)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "vnas01" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "group" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name $mode Total Data I/O ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    {
     "format": "ops",
     "label": "<--- Graph B ----- Graph A --->"
    }
   ],
   "targets": [
    {
     "alias": "TotalA $metric_a",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "$metric_a" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    },
    {
     "alias": "TotalB $metric_b",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "$metric_b" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    },
    {
     "alias": "TotalC $metric_a",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "$metric_a" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    },
    {
     "alias": "TotalD $metric_b",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "select": [
      [
       { "params": [ "$metric_b" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_$mode" }
     ]
    },
    {
     "alias": "a.$metric_a.[[tag_user]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"$mode\" FROM (SELECT sum(\"$metric_a\") AS \"user\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'user') GROUP BY time($buckets), \"user\" fill(0)) WHERE $timeFilter GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "b.$metric_b.[[tag_user]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"$mode\" FROM (SELECT sum(\"$metric_b\") AS \"user\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'user') GROUP BY time($buckets), \"user\" fill(0)) WHERE $timeFilter GROUP BY \"user\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "a.$metric_a.[[tag_client]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"$mode\" FROM (SELECT sum(\"$metric_a\") AS \"client\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'client') GROUP BY time($buckets), \"client\" fill(0)) WHERE $timeFilter GROUP BY \"client\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "b.$metric_b.[[tag_client]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"$mode\" FROM (SELECT sum(\"$metric_b\") AS \"client\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'client') GROUP BY time($buckets), \"client\" fill(0)) WHERE $timeFilter GROUP BY \"client\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "content": "<style>\n.hr-text {\n  line-height: 1em;\n  position: relative;\n  outline: 0;\n  border: 0;\n  color: black;\n  text-align: center;\n  height: 1.5em;\n  opacity: .5;\n  font-family: Futura, sans-serif;\n}\n.hr-text:before {\n  content: '';\n  background: -webkit-gradient(linear, left top, right top, from(transparent), color-stop(#818078), to(transparent));\n  background: linear-gradient(to right, transparent, #FFFFFF, transparent);\n  position: absolute;\n  left: 0;\n  top: 50%;\n  width: 100%;\n  height: 1px;\n}\n.hr-text:after {\n  content: attr(data-content);\n  position: relative;\n  display: inline-block;\n  color: black;\n  padding: 0 .5em;\n  line-height: 1.5em;\n  color: #FFFFFF;\n  background-color: #161719;\n  white-space: pre;\n  margin-top: -9px;\n}\n</style>\n<table align=\"center\" width=\"100%\" height=\"100%\" style=\"border: 0px\">\n  <tr><td style=\"border: 0px\">\n    <hr align=\"center\" class=\"hr-text\" data-content=\"^ USERS/CLIENTS ^\nv NODES v\">\n  </td></tr>\n</table>"
  },
  {
   "title": "$colo $name Node Total Data I/O ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "<--- Write/In ----- Read/Out --->"
    }
   ],
   "targets": [
    {
     "alias": "rd.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"read_bytes\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(0)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "wr.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"write_bytes\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(0)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "Total Read (Out)",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"read_bytes\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    },
    {
     "alias": "Total Write (In)",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"write_bytes\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Node Total Data I/O Requests ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Reqs" }
   ],
   "targets": [
    {
     "alias": "reqs.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"reqs\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') AND $timeFilter GROUP BY time($buckets), \"server\" fill(0)",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "Total Reqs",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT sum(\"reqs\") FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') AND $timeFilter GROUP BY time($buckets) fill(0)",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    }
   ]
  },
  {
   "title": "$colo $name Node Total Data I/O Busy/Queue-Length ($buckets buckets)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "<--- Qlen ----- Bsy --->" }
   ],
   "targets": [
    {
     "alias": "bsy.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_bsy\" FROM (SELECT sum(\"bsy\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "qlen.[[tag_server]]",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_qlen\" FROM (SELECT sum(\"qlen\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter GROUP BY \"server\"",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "server" }
     ]
    },
    {
     "alias": "Total Bsy",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_bsy\" FROM (SELECT sum(\"bsy\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    },
    {
     "alias": "Total Qlen",
     "groupBy": [
      { "params": [ "$buckets" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tail",
     "query": "SELECT \"$show_qlen\" FROM (SELECT sum(\"qlen\") AS \"Show\" FROM \"tail\" WHERE (\"host\" = '$host' AND \"ident\" = 'total_server') GROUP BY time($buckets) fill(0)) WHERE $timeFilter",
     "select": [
      [
       { "params": [ "read_rate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "ident", "operator": "=", "value": "total_server" }
     ]
    }
   ]
  }
 ]
}